SELECT fact.id FROM fact;
SELECT departments.id FROM departments;
SELECT locations.id FROM locations;
SELECT fact.id, fact.dept_id FROM fact;
SELECT fact.id, fact.loc_id FROM fact;
SELECT departments.id, departments.dept_name FROM departments;
SELECT locations.id, locations.city FROM locations;
SELECT fact.id FROM fact WHERE fact.id > 0;
SELECT fact.id FROM fact WHERE fact.id <= 10;
SELECT fact.id FROM fact WHERE fact.id >= 100;
SELECT fact.id FROM fact WHERE fact.dept_id = 1;
SELECT fact.id FROM fact WHERE fact.dept_id = 999;
SELECT fact.id FROM fact WHERE fact.loc_id = 1;
SELECT fact.id FROM fact WHERE fact.loc_id <= 5;
SELECT fact.id FROM fact WHERE fact.loc_id >= 100;
SELECT departments.dept_name FROM departments WHERE departments.id = 1;
SELECT departments.dept_name FROM departments WHERE departments.id > 1;
SELECT locations.city FROM locations WHERE locations.id = 1;
SELECT locations.city FROM locations WHERE locations.id <= 10;
SELECT locations.city FROM locations WHERE locations.id >= 100;
SELECT fact.id, departments.dept_name FROM fact JOIN departments ON fact.dept_id = departments.id;
SELECT fact.id, locations.city FROM fact JOIN locations ON fact.loc_id = locations.id;
SELECT departments.dept_name, fact.id FROM departments JOIN fact ON departments.id = fact.dept_id;
SELECT locations.city, fact.id FROM locations JOIN fact ON locations.id = fact.loc_id;
SELECT fact.id, departments.dept_name FROM fact JOIN departments ON fact.dept_id = departments.id WHERE fact.id > 0;
SELECT fact.id, departments.dept_name FROM fact JOIN departments ON fact.dept_id = departments.id WHERE fact.id <= 10;
SELECT fact.id, departments.dept_name FROM fact JOIN departments ON fact.dept_id = departments.id WHERE departments.id = 1;
SELECT fact.id, departments.dept_name FROM fact JOIN departments ON fact.dept_id = departments.id WHERE departments.dept_name = 'Engineering';
SELECT fact.id, locations.city FROM fact JOIN locations ON fact.loc_id = locations.id WHERE fact.id > 0;
SELECT fact.id, locations.city FROM fact JOIN locations ON fact.loc_id = locations.id WHERE fact.id <= 10;
SELECT fact.id, locations.city FROM fact JOIN locations ON fact.loc_id = locations.id WHERE locations.id = 1;
SELECT fact.id, locations.city FROM fact JOIN locations ON fact.loc_id = locations.id WHERE locations.city = 'City 1';
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN departments ON fact.dept_id = departments.id JOIN locations ON fact.loc_id = locations.id;
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN locations ON fact.loc_id = locations.id JOIN departments ON fact.dept_id = departments.id;
SELECT departments.dept_name, locations.city, fact.id FROM departments JOIN fact ON departments.id = fact.dept_id JOIN locations ON fact.loc_id = locations.id;
SELECT locations.city, departments.dept_name, fact.id FROM locations JOIN fact ON locations.id = fact.loc_id JOIN departments ON fact.dept_id = departments.id;
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN departments ON fact.dept_id = departments.id JOIN locations ON fact.loc_id = locations.id WHERE fact.id > 0;
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN departments ON fact.dept_id = departments.id JOIN locations ON fact.loc_id = locations.id WHERE fact.id <= 10;
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN departments ON fact.dept_id = departments.id JOIN locations ON fact.loc_id = locations.id WHERE fact.id >= 100;
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN departments ON fact.dept_id = departments.id JOIN locations ON fact.loc_id = locations.id WHERE fact.dept_id = 1;
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN departments ON fact.dept_id = departments.id JOIN locations ON fact.loc_id = locations.id WHERE fact.dept_id = 999;
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN departments ON fact.dept_id = departments.id JOIN locations ON fact.loc_id = locations.id WHERE fact.loc_id = 1;
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN departments ON fact.dept_id = departments.id JOIN locations ON fact.loc_id = locations.id WHERE fact.loc_id <= 5;
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN departments ON fact.dept_id = departments.id JOIN locations ON fact.loc_id = locations.id WHERE departments.id = 1;
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN departments ON fact.dept_id = departments.id JOIN locations ON fact.loc_id = locations.id WHERE locations.id = 1;
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN departments ON fact.dept_id = departments.id JOIN locations ON fact.loc_id = locations.id WHERE departments.dept_name = 'Engineering';
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN departments ON fact.dept_id = departments.id JOIN locations ON fact.loc_id = locations.id WHERE locations.city = 'City 1';
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN departments ON fact.dept_id = departments.id JOIN locations ON fact.loc_id = locations.id WHERE fact.id > 0 AND departments.id = 1;
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN departments ON fact.dept_id = departments.id JOIN locations ON fact.loc_id = locations.id WHERE fact.id > 0 AND locations.id = 1;
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN departments ON fact.dept_id = departments.id JOIN locations ON fact.loc_id = locations.id WHERE departments.id = 1 AND locations.id = 1;
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN departments ON fact.dept_id = departments.id JOIN locations ON fact.loc_id = locations.id WHERE fact.id <= 100 AND fact.loc_id <= 10;
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN departments ON fact.dept_id = departments.id JOIN locations ON fact.loc_id = locations.id WHERE fact.id >= 100 AND fact.loc_id >= 10;
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN departments ON fact.dept_id = departments.id JOIN locations ON fact.loc_id = locations.id WHERE fact.dept_id = 1 AND fact.loc_id <= 10;
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN departments ON fact.dept_id = departments.id JOIN locations ON fact.loc_id = locations.id WHERE departments.dept_name = 'Engineering' AND locations.city = 'City 1';
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN locations ON fact.loc_id = locations.id JOIN departments ON fact.dept_id = departments.id WHERE fact.id > 0;
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN locations ON fact.loc_id = locations.id JOIN departments ON fact.dept_id = departments.id WHERE fact.id <= 10;
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN locations ON fact.loc_id = locations.id JOIN departments ON fact.dept_id = departments.id WHERE fact.id >= 100;
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN locations ON fact.loc_id = locations.id JOIN departments ON fact.dept_id = departments.id WHERE fact.dept_id = 1;
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN locations ON fact.loc_id = locations.id JOIN departments ON fact.dept_id = departments.id WHERE fact.loc_id = 1;
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN locations ON fact.loc_id = locations.id JOIN departments ON fact.dept_id = departments.id WHERE departments.id = 1;
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN locations ON fact.loc_id = locations.id JOIN departments ON fact.dept_id = departments.id WHERE locations.id = 1;
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN locations ON fact.loc_id = locations.id JOIN departments ON fact.dept_id = departments.id WHERE departments.dept_name = 'Engineering';
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN locations ON fact.loc_id = locations.id JOIN departments ON fact.dept_id = departments.id WHERE locations.city = 'City 1';
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN locations ON fact.loc_id = locations.id JOIN departments ON fact.dept_id = departments.id WHERE fact.id > 0 AND departments.id = 1;
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN locations ON fact.loc_id = locations.id JOIN departments ON fact.dept_id = departments.id WHERE fact.id > 0 AND locations.id = 1;
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN locations ON fact.loc_id = locations.id JOIN departments ON fact.dept_id = departments.id WHERE departments.id = 1 AND locations.id = 1;
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN locations ON fact.loc_id = locations.id JOIN departments ON fact.dept_id = departments.id WHERE fact.id <= 100 AND fact.loc_id <= 10;
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN locations ON fact.loc_id = locations.id JOIN departments ON fact.dept_id = departments.id WHERE fact.id >= 100 AND fact.loc_id >= 10;
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN locations ON fact.loc_id = locations.id JOIN departments ON fact.dept_id = departments.id WHERE fact.dept_id = 1 AND fact.loc_id <= 10;
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN locations ON fact.loc_id = locations.id JOIN departments ON fact.dept_id = departments.id WHERE departments.dept_name = 'Engineering' AND locations.city = 'City 1';
SELECT fact.id FROM fact WHERE fact.id > 0 AND fact.id <= 100;
SELECT fact.id FROM fact WHERE fact.id > 100 AND fact.id <= 500;
SELECT fact.id FROM fact WHERE fact.id > 500 AND fact.id <= 1000;
SELECT fact.id FROM fact WHERE fact.dept_id = 1 AND fact.loc_id = 1;
SELECT fact.id FROM fact WHERE fact.dept_id = 1 AND fact.loc_id <= 10;
SELECT fact.id FROM fact WHERE fact.dept_id = 999 AND fact.loc_id >= 100;
SELECT fact.id FROM fact WHERE fact.loc_id > 10 AND fact.loc_id <= 20;
SELECT fact.id FROM fact WHERE fact.loc_id > 20 AND fact.loc_id <= 30;
SELECT departments.id FROM departments WHERE departments.id = 1 OR departments.id = 2;
SELECT locations.id FROM locations WHERE locations.id = 1 OR locations.id = 2;
SELECT fact.id FROM fact WHERE fact.dept_id = 1 OR fact.loc_id = 1;
SELECT fact.id FROM fact WHERE fact.id <= 10 OR fact.id >= 1000;
SELECT fact.id, departments.dept_name FROM fact JOIN departments ON fact.dept_id = departments.id WHERE fact.id <= 10 OR departments.id = 1;
SELECT fact.id, locations.city FROM fact JOIN locations ON fact.loc_id = locations.id WHERE fact.id <= 10 OR locations.id = 1;
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN departments ON fact.dept_id = departments.id JOIN locations ON fact.loc_id = locations.id WHERE departments.id = 1 OR locations.id = 1;
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN locations ON fact.loc_id = locations.id JOIN departments ON fact.dept_id = departments.id WHERE departments.id = 1 OR locations.id = 1;
SELECT fact.id, departments.dept_name FROM fact JOIN departments ON fact.dept_id = departments.id WHERE fact.dept_id <> 999;
SELECT fact.id, locations.city FROM fact JOIN locations ON fact.loc_id = locations.id WHERE fact.loc_id <> 1;
SELECT fact.id FROM fact WHERE fact.id <> 1;
SELECT departments.dept_name FROM departments WHERE departments.dept_name <> 'Engineering';
SELECT locations.city FROM locations WHERE locations.city <> 'City 1';
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN departments ON fact.dept_id = departments.id JOIN locations ON fact.loc_id = locations.id WHERE fact.id <> 1;
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN locations ON fact.loc_id = locations.id JOIN departments ON fact.dept_id = departments.id WHERE fact.id <> 1;
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN departments ON fact.dept_id = departments.id JOIN locations ON fact.loc_id = locations.id WHERE fact.dept_id <> 999 AND locations.id <= 10;
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN locations ON fact.loc_id = locations.id JOIN departments ON fact.dept_id = departments.id WHERE fact.dept_id <> 999 AND locations.id <= 10;
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN departments ON fact.dept_id = departments.id JOIN locations ON fact.loc_id = locations.id WHERE departments.dept_name <> 'Engineering' OR locations.city = 'City 1';
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN locations ON fact.loc_id = locations.id JOIN departments ON fact.dept_id = departments.id WHERE departments.dept_name <> 'Engineering' OR locations.city = 'City 1';
SELECT fact.id, departments.dept_name FROM fact JOIN departments ON fact.dept_id = departments.id WHERE fact.id > 0 AND departments.dept_name = 'Engineering';
SELECT fact.id, locations.city FROM fact JOIN locations ON fact.loc_id = locations.id WHERE fact.id > 0 AND locations.city = 'City 1';
SELECT fact.id, departments.dept_name, locations.city FROM fact JOIN departments ON fact.dept_id = departments.id JOIN locations ON fact.loc_id = locations.id WHERE fact.id > 0 AND departments.dept_name = 'Engineering' AND locations.city = 'City 1';
